### ISSUE TITLE
Translation to java or compilation to bytecode?

### ISSUE THREAD

**Issue by eugene-nikolaev** [cqfn/eo#14]
Hello!
Quoting the README:

```
We want EO to be compilable to Java. We want to stay as close to Java and JVM as possible, mostly in order to re-use the eco-system and libraries already available.
```

```
This code will compile into a .java class that will compile into a .class byte code that will run and print "Hello, world!".
...
```

Why don't it compile directly to the bytecode as Scala, Groovy, etc?
It would still be anyway able to use all the benefits of java eco-system.
This would eliminate an extra translation step.
Also, I guess it could be more natural for building, e.g. for Maven.

**Comment by yegor256** [comment]
@evgeniynickolaev I actually always was asking myself why that Scala, Groovy, Kotlin and other languages don't compile to Java. Why implementing `javac` from scratch? It will be much easier to compile into `.java` files than to byte-code, right? So, why making our life more complex?

**Comment by evgeniynickolaev** [comment]
Yes, that sounds reasonable. But will the extra step fit well into existing building tools (say Maven)? Or IDEs.

**Comment by yegor256** [comment]
@evgeniynickolaev well, I think so. There is `generate-sources` build phase in Maven -- our plugin will stay right there and produce `.java` files into `target/generated-sources` directory, just like ANTL4 plugin works. And we will also be able to integrate with IDEs, in a similar way. Make sense?

**Comment by evgeniynickolaev** [comment]
Yes, thanks, I agree it could be easier to implement.

I've just discussed Scala/Groovy with a colleague who has switched to Scala.
Some of their constructs fit to bytecode but not to Java.
Also he supposed they had made compilers not translators for the sake of performance.
And even so they are too slow.
One more reason is debugging and line number matching)
Not sure it is a big reason because of this: http://www.yegor256.com/2016/02/09/are-you-still-debugging.html
But scala, groovy etc definitely needed it.

To be honest I am a little bit scared to stay without any debugger by mental inertia)
On the other side, we'll anyway still be able to debug awkward java 3rd-parties (eco-system!).

**Comment by stain** [comment]
I think it's a good way to start - we discussed earlier that there could be two options, compile through `.java` or straight to `.class` (which could do further optimizations as the JVM bytecode in some respect has more flexibility than Java).

You could even do an "interpreted" mode using a JVM Lisp language like Clojure - it's easyt to write LISP in LISP - which Clojure already can compile straight to JVM bytecode. Looking at the current simple EO proposal this could also be an interesting and not too difficult approach.

**Comment by evgeniynickolaev** [comment]
Yes, I agree, for now .java is enough and .class maybe added later if needed.

But I am concerned that bringing one more complex thing like Clojure, which has its own bugs, will simplify the development:

![image](https://cloud.githubusercontent.com/assets/305699/20492539/27766c46-b026-11e6-9830-96f2ec95bff3.png)

Some of them are opened for years.
So, I'd prefer a "fluent translator")

**Comment by yegor256** [comment]
@eugene-nikolaev we translate to Java now out of the box

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#14` is not assigned, can't get performer
