### ISSUE TITLE
Laziness vs. assignment: exponential run time of a linear code!

### ISSUE THREAD

**Issue by dours** [cqfn/eo#417]
I've generated a purely functional/immutable test, which runs in exponential time with the EO translator "as is", but in linear time with memoization in the runtime library (see commit https://github.com/dours/eo/commit/3dfcf237514c8ddf0c02405ea127196842e20168 for details). 

The memoization breaks mutable code (memory and random), so I do not do a pull request. I need some suggestions on how to proceed with this.

**Comment by yegor256** [comment]
@dours very good point, let me investigate

**Comment by yegor256** [comment]
@dours the problem is in the duplicate calculation while "getting" attributes. This test should pass, but it fails:

```java
public final class AtDecoratedTest {
    @Test
    public void readsOnlyOnce() {
        final Dummy dummy = new Dummy(Phi.Φ);
        final Phi neg = dummy.attr("neg").get();
        neg.attr("Δ").get();
        MatcherAssert.assertThat(
            dummy.count,
            Matchers.equalTo(1)
        );
    }
    public static class Dummy extends PhDefault {
        public int count;
        public Dummy(final Phi sigma) {
            super(sigma);
            this.add("φ", new AtComposite(
                this, rho -> {
                ++this.count;
                return new Data.ToPhi(1L);
            }));
        }
    }
}
```

The EO code would be this:

```
dummy.neg # here we have TWO calculations
[] > dummy
  1 > @
```

Instead of two calculations, we should have only one. I think we should "cache" the calculation that happens when we traverse through the "@" attribute.

Maybe you can fix it?

**Comment by yegor256** [comment]
@dours I meant fixing the test I suggested. It doesn't pass now, but it should. We should not calculate an atom twice. But now we do. In the `AtDecoratedTest` example above, we calculate it first time in order to get the `neg` atom from the number, and the second time when the `neg` atom gets the get the number from the parent. This duplication leads to the problem you mentioned in this ticket, I believe: too many calculations of atoms, which grow exponentially.

**Comment by yegor256** [comment]
@dours what do you think will `x` be equal to, instead of one:

```
[] > calculates-only-once
  memory > x
  [] > a
    seq > @
      x.write (x.add 1)
      42
  and. > @
    x.write 0
    a.neg.neg.neg.neg.neg.neg.eq 42
    x.eq 1
```

The answer is 14, which is wrong, I believe. I'm thinking about how to fix this...

**Comment by dours** [comment]
@yegor256 well, I believe, mixing laziness and assignments must be fun anyway. In other words, I need to investigate...

**Comment by yegor256** [comment]
@dours try version 0.16.12
