### ISSUE TITLE
`int.as-bytes` is broken

### ISSUE THREAD

**Issue by IngeniariusSoftware** [cqfn/eo#605]
```java
+package c2eo.src.app

+alias org.eolang.gray.ram
+alias org.eolang.io.stdout
+alias org.eolang.txt.sprintf

[] > app
  ram 1024 > r
  seq > @
    r.write 0 (3.as-bytes)
    stdout (sprintf "%d\n" ((r.read 0 8).as-int))
```

output
```
> 216172782113783808
```

It seems to be related to https://github.com/cqfn/eo/commit/cdfa8f0426d7aa8ec8768c4a9fe9b33b358e9c74 and I assume that this is due to the fact that `BigInteger` does not use all 8 bytes to write Long, but the minimum required

**Comment by yegor256** [comment]
@andreoss can you please here please?

**Comment by andreoss** [comment]
@IngeniariusSoftware 
There was an inconsistency before https://github.com/cqfn/eo/commit/cdfa8f0426d7aa8ec8768c4a9fe9b33b358e9c74,  bytes were treated as `Long` and as `BigInteger`, now it's only `BigInteger`. 

 `BigInteger` seemed to be preferable because 
1) it's platform independent (always big-endian) and 
2) defines shift operations we need.
i.e `int.as-bytes.not.as-int` produces an expected result

though byte representation uses minimum number of bytes required (can be more than 8). 

@yegor256 Should `int.as-bytes` always have only meaningful bytes or always be 8 bytes?

**Comment by yegor256** [comment]
@andreoss `int.as-bytes` should always return an array of 8 bytes.

**Comment by yegor256** [comment]
@IngeniariusSoftware @andreoss version 0.22.2 release, which includes these changes. Maybe you can try it out?
